import pandas as pd    
import numpy as np     # numpy — for numerical operations
from sklearn.ensemble import IsolationForest    # the ML model we use to detect anomalies
from sklearn.preprocessing import StandardScaler  
from thefuzz import fuzz    # fuzzy matching-it finds similar strings (for duplicate detection)
from datetime import datetime # for date validation
import os    

def load_invoices_csv():
    """Load the invoices CSV generated by parser.py"""
    
   
    csv_path = os.path.join(os.path.dirname(__file__), 'output', 'invoices.csv')
    
    # if the file doesn't exist, parser.py hasn't been run yet
    if not os.path.exists(csv_path):
        print("invoices.csv not found! Run parser.py first.")
        return None
    
    # read the CSV into a pandas DataFrame
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} invoices from CSV")
    return df

def calculate_zscore(df):
    """
    Calculate Z-score for each invoice amount per vendor.
    
    Z-score tells us how far an amount is from that vendor's average.
    For example: if a vendor usually bills $500 but suddenly bills $5000,
    the Z-score will be very high — flagging it as suspicious.
    Z-score > 2 means the amount is unusually high or low for that vendor.
    """
    df = df.copy()
    
    # start everyone at 0 — will update for vendors with multiple invoices
    df['zscore'] = 0.0

    # convert Total Amount to numbers safely
    # some values might be "NOT FOUND" strings — those become 0
    df['Total Amount'] = pd.to_numeric(
        df['Total Amount'].astype(str).str.replace(',', ''),
        errors='coerce'
    ).fillna(0.0)

    # calculate z-score separately for each vendor
    # this is important — we compare each invoice to THAT vendor's history
    # not to all invoices together
    for vendor in df['Vendor Name'].unique():
        
        # skip vendors where name wasn't extracted
        if vendor == "NOT FOUND":
            continue
        
        vendor_mask = df['Vendor Name'] == vendor
        vendor_amounts = df.loc[vendor_mask, 'Total Amount']
        
        # need at least 2 invoices from same vendor to calculate z-score
        if len(vendor_amounts) > 1:
            mean = vendor_amounts.mean()
            std  = vendor_amounts.std()
            
            # avoid division by zero if all amounts are identical
            if std > 0:
                df.loc[vendor_mask, 'zscore'] = (
                    vendor_amounts - mean
                ) / std

    return df

def run_isolation_forest(df):
    """
    Use Isolation Forest to detect anomalies in the dataset.
    
    Isolation Forest is an unsupervised ML algorithm — it doesn't need
    labelled data to learn. It works by randomly splitting the data and
    checking how quickly each point gets 'isolated'. Anomalies get isolated
    faster because they are different from the rest of the data.
    
    We use two features: Total Amount and Line Items Count.
    An invoice with an unusually high amount AND unusual item count
    is more likely to be flagged.
    """
    
    # select the features we want the model to look at
    features = df[['Total Amount', 'Line Items Count']].copy()
    
    # make sure both columns are numbers
    features['Total Amount'] = pd.to_numeric(
        features['Total Amount'], errors='coerce'
    ).fillna(0.0)
    features['Line Items Count'] = pd.to_numeric(
        features['Line Items Count'], errors='coerce'
    ).fillna(0.0)

    # scale the features so both are on the same range
    # without this, "Total Amount" (in thousands) would overpower
    # "Line Items Count" (small numbers like 3, 5, 7)
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)

    # contamination=0.1 means we expect about 10% of invoices to be anomalies
    # random_state=42 makes results reproducible every time we run
    model = IsolationForest(contamination=0.1, random_state=42)
    df['isolation_flag'] = model.fit_predict(features_scaled)
    
    # Isolation Forest returns -1 for anomalies and 1 for normal
    # we convert that to True/False for readability
    df['is_anomaly_ml'] = df['isolation_flag'].apply(
        lambda x: True if x == -1 else False
    )

    return df

def detect_duplicates(df):
    """
    Find invoices that might be duplicate payments.
    
    We use fuzzy matching to compare invoice numbers —
    this catches cases where numbers are slightly different due to
    typos or OCR errors, but the amounts match exactly.
    For example: invoice "51109338" vs "51109388" with the same amount
    would be flagged as a potential duplicate.
    """
    duplicates = []
    invoice_numbers = df['Invoice Number'].tolist()

    # compare every invoice against every other invoice (pairwise)
    for i in range(len(invoice_numbers)):
        for j in range(i + 1, len(invoice_numbers)):
            
            # skip if either invoice number wasn't extracted
            if (str(invoice_numbers[i]) == "NOT FOUND" or
                str(invoice_numbers[j]) == "NOT FOUND"):
                continue
            
            # fuzz.ratio gives a similarity score from 0 to 100
            # 100 means identical, 85+ means very similar
            score = fuzz.ratio(
                str(invoice_numbers[i]),
                str(invoice_numbers[j])
            )
            amount_i = df.iloc[i]['Total Amount']
            amount_j = df.iloc[j]['Total Amount']
            
            # flag as duplicate only if BOTH conditions are true:
            # 1. invoice numbers are very similar (>85% match)
            # 2. amounts are exactly the same
            if score > 85 and amount_i == amount_j:
                duplicates.append({
                    "Invoice 1":        invoice_numbers[i],
                    "Invoice 2":        invoice_numbers[j],
                    "Similarity Score": score,
                    "Amount":           amount_i
                })

    return duplicates

def check_date_logic(df):
    """
    Rule-based date validation.
    Flags:
    1. Future dates (date > today) — clearly wrong, invoices can't be from the future(flag as anomaly)
    2. Missing dates — date wasn't extracted by parser
    3. Invalid date formats — OCR read the date in an unrecognizable format

    Note: Old invoice check (>90 days) is intentionally disabled
    because this dataset is historical (2011-2021). In a real
    production system, invoices older than 90 days would be flagged.
    """
    today = datetime.today()
    date_flags = []

    for _, row in df.iterrows():
        flag = "None"  # default — no issue
        date_str = str(row['Date'])

        # if parser couldn't find a date, flag it
        if date_str == "NOT FOUND":
            flag = "Date missing"
            date_flags.append(flag)
            continue

        try:
            # try to parse the date string into a proper date object
            date = datetime.strptime(date_str, "%m/%d/%Y")

            # an invoice dated in the future is clearly wrong
            if date > today:
                flag = f"Future date detected ({date_str})"

        except:
            # if parsing fails, the date format is unrecognizable
            flag = f"Invalid date format ({date_str})"

        date_flags.append(flag)

    df['date_flag'] = date_flags
    return df

def generate_anomaly_reason(row):
    """
    Build a human-readable explanation for why an invoice was flagged.
    Multiple reasons can apply to the same invoice — they get joined with '|'.
    """
    reasons = []

    try:
        amount = float(row['Total Amount'])
    except:
        amount = 0.0

    # reason 1: z-score too high — unusual amount compared to this vendor's history
    if abs(row['zscore']) > 2:
        reasons.append(
            f"Unusual amount for vendor (Z-score: {row['zscore']:.2f})"
        )

    # reason 2: isolation forest flagged this invoice as an outlier
    if row['is_anomaly_ml']:
        reasons.append("Flagged by Isolation Forest")

    # reason 3: amount is exactly zero — either extraction failed or suspicious
    if amount == 0.0:
        reasons.append("Zero amount — missing or suspicious")

    # reason 4: amount is suspiciously small — likely an error
    if 0 < amount < 10:
        reasons.append(f"Suspiciously low amount (${amount})")

    # reason 5: amount is extremely large — needs human review
    if amount > 50000:
        reasons.append(f"Unusually high amount (${amount})")

    # reason 6: date issue found by check_date_logic
    if row.get('date_flag', 'None') != 'None':
        reasons.append(row['date_flag'])

    # join all reasons with a pipe separator
    # if no reasons, return "None" meaning the invoice is clean
    return " | ".join(reasons) if reasons else "None"

def run_anomaly_detection(df):
    """
    Master function that runs all 4 anomaly detection steps in order.
    Returns the updated DataFrame and a list of duplicate pairs found.
    """
    print("\nRunning anomaly detection...")

    # step 1: statistical check — is this amount unusual for this vendor?
    print("   Step 1: Z-score analysis...")
    df = calculate_zscore(df)

    # step 2: ML check — does this invoice look different from the rest?
    print("   Step 2: Isolation Forest ML...")
    df = run_isolation_forest(df)

    # step 3: duplicate check — has this invoice been submitted before?
    print("   Step 3: Duplicate detection...")
    duplicates = detect_duplicates(df)

    # step 4: date check — is the date valid and sensible?
    print("   Step 4: Date logic validation...")
    df = check_date_logic(df)

    # combine ALL anomaly conditions into one final True/False column
    # an invoice is flagged if ANY of these conditions are true
    df['is_anomaly'] = (
        (abs(df['zscore']) > 2) |              # unusual for vendor
        df['is_anomaly_ml'] |                  # ML flagged
        (df['Total Amount'] == 0.0) |          # zero amount
        (df['Total Amount'].between(0.01, 10)) | # suspiciously low
        (df['Total Amount'] > 50000) |         # unusually high
        (df['date_flag'].str.contains('Future', na=False)) |  # future date
        (df['date_flag'].str.contains('missing', na=False)) | # missing date
        (df['date_flag'].str.contains('Invalid', na=False))   # bad date format
    )

    # generate a human-readable reason for each flagged invoice
    df['anomaly_reason'] = df.apply(generate_anomaly_reason, axis=1)

    return df, duplicates

def save_results(df, duplicates):
    """Save the final anomaly detection results to CSV files."""
    
    output_dir = os.path.join(os.path.dirname(__file__), 'output')
    os.makedirs(output_dir, exist_ok=True)

    # save the main results — one row per invoice with anomaly info
    output_csv = os.path.join(output_dir, 'anomaly_results.csv')
    df[['Filename', 'Invoice Number', 'Vendor Name',
        'Total Amount', 'Date', 'date_flag',
        'zscore', 'is_anomaly',
        'anomaly_reason']].to_csv(output_csv, index=False)
    print(f"\nResults saved to: output/anomaly_results.csv")

    # if duplicates were found, save them separately for easy review
    if duplicates:
        dup_df = pd.DataFrame(duplicates)
        dup_csv = os.path.join(output_dir, 'duplicates.csv')
        dup_df.to_csv(dup_csv, index=False)
        print(f"Duplicates saved to: output/duplicates.csv")

if __name__ == "__main__":
    
    # load the invoices CSV that parser.py generated
    df = load_invoices_csv()
    if df is None:
        exit()

    # run the full anomaly detection pipeline
    df, duplicates = run_anomaly_detection(df)

    # count how many anomalies were found
    total     = len(df)
    anomalies = df[df['is_anomaly'] == True]

    # print a clean summary
    print(f"\n{'='*50}")
    print(f"ANOMALY DETECTION SUMMARY")
    print(f"{'='*50}")
    print(f"Total invoices analysed : {total}")
    print(f"Anomalies detected      : {len(anomalies)}")
    print(f"Clean invoices          : {total - len(anomalies)}")
    print(f"Duplicate pairs found   : {len(duplicates)}")
    print(f"{'='*50}")

    # break down exactly WHY invoices were flagged
    print(f"\nBreakdown of anomaly reasons:")
    print(f"   ML flagged (Isolation Forest) : "
          f"{len(df[df['is_anomaly_ml'] == True])}")
    print(f"   Zero amounts                  : "
          f"{len(df[df['Total Amount'] == 0.0])}")
    print(f"   Very low amounts (<$10)       : "
          f"{len(df[df['Total Amount'].between(0.01, 10)])}")
    print(f"   Very high amounts (>$50k)     : "
          f"{len(df[df['Total Amount'] > 50000])}")
    print(f"   Future dates                  : "
          f"{len(df[df['date_flag'].str.contains('Future', na=False)])}")
    print(f"   Missing dates                 : "
          f"{len(df[df['date_flag'].str.contains('missing', na=False)])}")

    # show the list of flagged invoices
    if len(anomalies) > 0:
        print(f"\nFlagged Invoices:")
        print(anomalies[['Invoice Number', 'Vendor Name',
                         'Total Amount', 'Date',
                         'anomaly_reason']].to_string(index=False))

    # show duplicate pairs if any were found
    if duplicates:
        print(f"\nDuplicate Pairs:")
        for d in duplicates:
            print(f"   {d['Invoice 1']} & {d['Invoice 2']} "
                  f"(similarity: {d['Similarity Score']}%, "
                  f"amount: {d['Amount']})")
    else:
        print("\nNo duplicates found.")

    # save everything to CSV files
    save_results(df, duplicates)
    print("\nAnomaly detection complete.")